ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-0.eastus.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-1.eastus.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-2.eastus.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-3.eastus.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-4.eastus.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-5.eastus.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-6.eastus.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-7.eastus.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-8.eastus.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-9.eastus.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-0.eastus2.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-1.eastus2.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-2.eastus2.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-3.eastus2.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-4.eastus2.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-5.eastus2.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-6.eastus2.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-7.eastus2.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-8.eastus2.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-9.eastus2.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-0.japaneast.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-1.japaneast.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-2.japaneast.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-3.japaneast.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-4.japaneast.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-5.japaneast.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-6.japaneast.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-7.japaneast.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-8.japaneast.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456
ssh -i  ssh-keys/terraform-azure.pem -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-9.japaneast.cloudapp.azure.com az login -u asreet-tech@atttrainings.com -p Azure@123456


ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-0.eastus.cloudapp.azure.com az account set --subscription '6378784e-0a8a-4197-a15d-afc70adb2952'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-1.eastus.cloudapp.azure.com az account set --subscription '6378784e-0a8a-4197-a15d-afc70adb2952'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-2.eastus.cloudapp.azure.com az account set --subscription '6378784e-0a8a-4197-a15d-afc70adb2952'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-3.eastus.cloudapp.azure.com az account set --subscription '6378784e-0a8a-4197-a15d-afc70adb2952'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-4.eastus.cloudapp.azure.com az account set --subscription '6378784e-0a8a-4197-a15d-afc70adb2952'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-5.eastus.cloudapp.azure.com az account set --subscription '6378784e-0a8a-4197-a15d-afc70adb2952'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-6.eastus.cloudapp.azure.com az account set --subscription '18c950cd-7d1d-4834-a27b-ce656074eea1'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-7.eastus.cloudapp.azure.com az account set --subscription '18c950cd-7d1d-4834-a27b-ce656074eea1'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-8.eastus.cloudapp.azure.com az account set --subscription '18c950cd-7d1d-4834-a27b-ce656074eea1'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-0-9.eastus.cloudapp.azure.com az account set --subscription '18c950cd-7d1d-4834-a27b-ce656074eea1'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-0.eastus2.cloudapp.azure.com az account set --subscription '18c950cd-7d1d-4834-a27b-ce656074eea1'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-1.eastus2.cloudapp.azure.com az account set --subscription '18c950cd-7d1d-4834-a27b-ce656074eea1'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-2.eastus2.cloudapp.azure.com az account set --subscription '81b49d19-6ecd-4a24-96f4-95ec17aa6799'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-3.eastus2.cloudapp.azure.com az account set --subscription '81b49d19-6ecd-4a24-96f4-95ec17aa6799'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-4.eastus2.cloudapp.azure.com az account set --subscription '81b49d19-6ecd-4a24-96f4-95ec17aa6799'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-5.eastus2.cloudapp.azure.com az account set --subscription '81b49d19-6ecd-4a24-96f4-95ec17aa6799'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-6.eastus2.cloudapp.azure.com az account set --subscription '81b49d19-6ecd-4a24-96f4-95ec17aa6799'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-7.eastus2.cloudapp.azure.com az account set --subscription '81b49d19-6ecd-4a24-96f4-95ec17aa6799'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-8.eastus2.cloudapp.azure.com az account set --subscription 'd7c166d0-9efb-412b-bdbc-0fa80d587141'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-1-9.eastus2.cloudapp.azure.com az account set --subscription 'd7c166d0-9efb-412b-bdbc-0fa80d587141'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-0.japaneast.cloudapp.azure.com az account set --subscription 'd7c166d0-9efb-412b-bdbc-0fa80d587141'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-1.japaneast.cloudapp.azure.com az account set --subscription 'd7c166d0-9efb-412b-bdbc-0fa80d587141'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-2.japaneast.cloudapp.azure.com az account set --subscription 'd7c166d0-9efb-412b-bdbc-0fa80d587141'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-3.japaneast.cloudapp.azure.com az account set --subscription 'd7c166d0-9efb-412b-bdbc-0fa80d587141'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-4.japaneast.cloudapp.azure.com az account set --subscription 'f674fa1e-9377-49a4-8ef7-a3049a97702e'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-5.japaneast.cloudapp.azure.com az account set --subscription 'f674fa1e-9377-49a4-8ef7-a3049a97702e'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-6.japaneast.cloudapp.azure.com az account set --subscription 'f674fa1e-9377-49a4-8ef7-a3049a97702e'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-7.japaneast.cloudapp.azure.com az account set --subscription 'f674fa1e-9377-49a4-8ef7-a3049a97702e'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-8.japaneast.cloudapp.azure.com az account set --subscription 'f674fa1e-9377-49a4-8ef7-a3049a97702e'
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no tuser@lnx-hpqzdp-2-9.japaneast.cloudapp.azure.com az account set --subscription 'f674fa1e-9377-49a4-8ef7-a3049a97702e'


ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-0.eastus.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-0 --name aks-0  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-1.eastus.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-1 --name aks-1  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-2.eastus.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-2 --name aks-2  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-3.eastus.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-3 --name aks-3  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-4.eastus.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-4 --name aks-4  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-5.eastus.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-5 --name aks-5  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-6.eastus.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-0 --name aks-0  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-7.eastus.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-1 --name aks-1  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-8.eastus.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-2 --name aks-2  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-9.eastus.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-3 --name aks-3  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-0.eastus2.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-4 --name aks-4  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-1.eastus2.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-5 --name aks-5  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-2.eastus2.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-0 --name aks-0  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-3.eastus2.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-1 --name aks-1  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-4.eastus2.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-2 --name aks-2  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-5.eastus2.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-3 --name aks-3  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-6.eastus2.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-4 --name aks-4  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-7.eastus2.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-5 --name aks-5  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-8.eastus2.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-0 --name aks-0  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-9.eastus2.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-1 --name aks-1  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-0.japaneast.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-2 --name aks-2  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-1.japaneast.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-3 --name aks-3  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-2.japaneast.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-4 --name aks-4  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-3.japaneast.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-5 --name aks-5  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-4.japaneast.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-0 --name aks-0  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-5.japaneast.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-1 --name aks-1  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-6.japaneast.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-2 --name aks-2  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-7.japaneast.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-3 --name aks-3  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-8.japaneast.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-4 --name aks-4  --overwrite
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-9.japaneast.cloudapp.azure.com az aks get-credentials --resource-group rg-aks-5 --name aks-5  --overwrite


ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-0.eastus.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-1.eastus.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-2.eastus.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-3.eastus.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-4.eastus.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-5.eastus.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-6.eastus.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-7.eastus.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-8.eastus.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-0-9.eastus.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-0.eastus2.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-1.eastus2.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-2.eastus2.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-3.eastus2.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-4.eastus2.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-5.eastus2.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-6.eastus2.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-7.eastus2.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-8.eastus2.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-1-9.eastus2.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-0.japaneast.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-1.japaneast.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-2.japaneast.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-3.japaneast.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-4.japaneast.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-5.japaneast.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-6.japaneast.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-7.japaneast.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-8.japaneast.cloudapp.azure.com kubectl get nodes -o wide
ssh -i ssh-keys/terraform-azure.pem  -o StrictHostKeyChecking=no  tuser@lnx-hpqzdp-2-9.japaneast.cloudapp.azure.com kubectl get nodes -o wide
